db = {
    "posts": [
        {
            "id": 1,
            "title": "HTMX is awesome!",
            "content": "I just learned about HTMX and it's awesome!",
        },
        {
            "id": 2,
            "title": "This post is generated by ChatGPT",
            "content": "I'm a robot. I'm writing this post using ChatGPT.",
        },
        {
            "id": 3,
            "title": "I'm tired...",
            "content": "It's 3am and I want to sleep.",
        },
        {
            "id": 4,
            "title": "Hello world!",
            "content": "It's 3pm and I want to sleep.",
        },
    ]
}


def get_posts():
    return db["posts"]


def get_post(post_id: int):
    for post in db["posts"]:
        if post["id"] == post_id:
            return post
    return None


def update_post(post_id: int, title: str, content: str):
    for post in db["posts"]:
        if post["id"] == post_id:
            post["title"] = title
            post["content"] = content
